### ISSUE TITLE
Failed dial to '1235' from Olympus on Always on from FireFox (Chrome works fine)

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/olympus#3]
In the UI I see:

No Answer/Rejected! Your call to +1235 was not answered.

And in the JS console, after successful response to invite I see this:
"WebRTCommCall:onRtcPeerConnectionSetRemoteDescriptionErrorEvent():error={}" WebRTComm.js:4033:0
WebRTCommCall.prototype.onRtcPeerConnectionSetRemoteDescriptionErrorEvent() WebRTComm.js:4033
WebRTCommCall.prototype.onPrivateCallConnectorRemoteSdpAnswerEvent/<()

FireFox version is 38.0.1 on a Mac

**Comment by KietnaQuTak** [comment]
Hello. I'm experiencing the same issue. Olympus is working fine while trying to connect call on Chrome, but on Firefox I got onRtcPeerConnectionSetRemoteDescriptionErrorEvent. I have found dozens of post about general WebRTC problems with Firefox mostly from older versions (I'm aware of webrtc experimental state in FF) with some solutions like in those two examples [this one](http://stackoverflow.com/questions/25986267/webrtc-works-in-chrome-but-not-firefox) or [this one](http://stackoverflow.com/questions/25329135/webrtc-firefox-unable-to-recieve-video-as-callee) (both from StackOverflow), but advices from those post did not fixed the DescriptionErrorEvent.

Do You have any advices or maybe You can point me a right direction on how to deal with this problem? I would appreciate even entirely disabling video, because for my purpose I need only audio connection.

Firefox v42 and v41, Windows 7 64bit, also tested on Firefox for MacOS

PS. Sometimes after many failed connection try I'm experiencing different behaviour. Olympus does not get connection rejected at once, instead I can see "CONNECTING..." in $scope.inCall.intStatus but nothing else is happening. In JS console I can see "ICE failed, see about:webrtc for more details <unknown>", I can paste about:webrtc status if it could help. The only strange thing is that it's not happening every time. Mostly I have DescriptionErrorEvent mention above.

Best regards
Kietna Qu'Tak

**Comment by deruelle** [comment]
This seems to be an issue from the underlying webrtcomm library https://github.com/Mobicents/webrtcomm/issues/18

**Comment by KietnaQuTak** [comment]
Thanks deruelle, I appreciate Your response. I'm looking forward for updates.

Meantime I was digging around to find anything else. Since sometimes Firefox logs "ICE failed, see about:webrtc for more details" I thought it may be related to the [IP4 0.0.0.0.](https://groups.google.com/forum/#!msg/doubango/r_2OxUpxPks/r9V4P2NR7pEJ) found on Google Groups, but "IP4 0.0.0.0" appears to be in Firefox and Chrome. Also on [Anatomy of WebRTC SDP](https://webrtchacks.com/sdp-anatomy/) we can read for c= lines: "As ICE is mandatory in WebRTC the IP in the c-line is not going to be used." so I assume that ICE is not the case?

**Comment by atsakiridis** [comment]
I think route cause for this is: https://github.com/RestComm/mediaserver/issues/67

Here's a more full log:

```
WebRTCommCall:onPrivateCallConnectorRemoteSdpAnswerEvent() WebRTComm.js:3275:5
WebRTCommCall:onRtcPeerConnectionSetRemoteDescriptionErrorEvent():error={} WebRTComm.js:4033:1
WebRTCommCall.prototype.onRtcPeerConnectionSetRemoteDescriptionErrorEvent() WebRTComm.js:4033
WebRTCommCall.prototype.onPrivateCallConnectorRemoteSdpAnswerEvent/<() WebRTComm.js:3299

WebRTCommCall:onRtcPeerConnectionSetRemoteDescriptionErrorEvent(): this.peerConnection.signalingState=have-local-offer WebRTComm.js:4036:13
WebRTCommCall:onRtcPeerConnectionSetRemoteDescriptionErrorEvent(): this.peerConnection.iceGatheringState=complete WebRTComm.js:4037:13
WebRTCommCall:onRtcPeerConnectionSetRemoteDescriptionErrorEvent(): this.peerConnection.iceConnectionState=new WebRTComm.js:4038:13
WebRTCommCall:onRtcPeerConnectionSetRemoteDescriptionErrorEvent(): this.peerConnectionState=answer-received WebRTComm.js:4039:13
WebRTCommCall:onRtcPeerConnectionErrorEvent(): error=InvalidSessionDescriptionError: Invalid description, no fingerprint attribute WebRTComm.js:3476:5
WebRTCommCall:close()
```
