### ISSUE TITLE
Names list too big, and space between names is a lot.

### ISSUE THREAD

**Issue by leftyb** [RestComm/olympus#68]
No need to cover so much space with the contacts list, and maybe less space between contacts too.
Maybe add option for thumbnail resizing (small, large, etc ).

**Comment by ipsilantide** [comment]
At the end we will have rooms on top and individual contacts beneath them...Rooms will only have an icon. So the space will be less. For me thumbnails makes no sense in the contact list since they are so small that actually you can't see them...So we can give the option "photos" or "no photos (like slack)". 
Apart of that you are right even in the mock-ups we can leave less space between rooms or contacts.
![screen shot 2016-11-29 at 3 44 54 pm](https://cloud.githubusercontent.com/assets/17202395/20712201/cdbd2128-b64b-11e6-9b16-871b58184e3e.png)
